Models/Entity/Course_Detail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocTrucTuyen.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Detail
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string Descriptions { get; set; }
        public Nullable<long> Course_ID { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual Course Course { get; set; }
    }
}

Areas/Admin/Controllers/Course_DetailController.cs
using HocTrucTuyen.Models.Business;
using HocTrucTuyen.Models.Entity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HocTrucTuyen.Areas.Admin.Controllers
{
    public class Course_DetailController : Controller
    {
        private HocTrucTuyenEntities db = new HocTrucTuyenEntities();
        // GET: Admin/Course_Detail
        public ActionResult Index(long ID, int page = 1, int pagesize = 5)
        {
            ViewBag.Course = db.Courses.Find(ID);
            var model = db.Course_Detail.Where(x => x.Course_ID == ID).OrderBy(x => x.Created_Date).ToPagedList(page, pagesize);
            return View(model);
        }
       

        public ActionResult Add(long ID)
        {
            ViewBag.Course = db.Courses.Find(ID);
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(Course_Detail entity)
        {
            entity.Link = "https://www.youtube.com/embed/" + new CourseBusiness().GetLink(entity.Link);
            entity.Created_Date = DateTime.Now;
            db.Course_Detail.Add(entity);
            db.SaveChanges();
            TempData["add_success"] = "Thêm bài giảng thành công.";
            return RedirectToAction("Index", new { ID = entity.Course_ID});
        }
      

        public ActionResult Edit(long ID)
        {
            ViewBag.detail = db.Course_Detail.Find(ID);
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Course_Detail entity)
        {
            var course = db.Course_Detail.Find(entity.ID);
            course.Link = "https://www.youtube.com/embed/" + new CourseBusiness().GetLink(entity.Link);
            course.Name = entity.Name;
            course.Descriptions = entity.Descriptions;
            db.SaveChanges();
            TempData["add_success"] = "Sửa bài giảng thành công.";
            return RedirectToAction("Index", new { ID = course.Course_ID });
        }

        public JsonResult Delete(long ID)
        {
            try
            {
                var course = db.Course_Detail.Find(ID);
                db.Course_Detail.Remove(course);
                db.SaveChanges();
                return Json(new
                {
                    status = true
                });
            }
            catch
            {
                return Json(new
                {
                    status = false
                });
            }
            
        }
    }
}

Areas/Admin/Views/Course_Detail/Add.cshtml
@{
    ViewBag.Title = "Thêm bài giảng";
    Layout = "~/Areas/Admin/Views/Shared/_layout.cshtml";
    var course = ViewBag.Course as HocTrucTuyen.Models.Entity.Course;
}

<div id="page-wrapper" style="min-height: 356px;">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Thêm bài giảng cho khóa học: <span style="color: blue">@course.Title</span></h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Thêm bài giảng
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-6">
                                @using (Html.BeginForm("Add", "Course_Detail", FormMethod.Post, new { id = "frmAddCourse", enctype = "multipart/form-data" }))
                                {
                                    <input type="hidden" name="Course_ID" value="@course.ID"/>
                                    <div class="form-group">
                                        <label>Tên bài giảng</label><span style="color:red">(*)</span>
                                        <input type="text" class="form-control" name="Name" placeholder="Nhập tiêu đề">
                                    </div>
                                    <div class="form-group">
                                        <label>Link Youtube</label><span style="color:red">(*)</span>
                                        <input type="text" class="form-control" name="Link" placeholder="Nhập link youtube" />
                                    </div>
                                    <div class="form-group">
                                        <label>Nội dung </label><span style="color:red">(*)</span>
                                        <textarea name="Descriptions" id="text_Description" rows="6" placeholder="Nhập nội dung" class="form-control">
                                        </textarea>
                                    </div>

                                    <button type="submit" class="btn btn-default">Thêm mới</button>
                                }

                            </div>

                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>

@section jsFooter{

    <script type="text/javascript">

        $(document).ready(function () {
            //validate form
            CKEDITOR.replace('text_Description');
            $("#frmAddCourse").validate({
                rules: {
                    Name: "required",
                    Link: "required",
                    Descriptions: "required"
                },
                messages: {
                    Name: "Vui lòng nhập tên bài giảng",
                    Link: "Vui lòng nhập link youtube",
                    Descriptions: "Vui lòng nhập nội dung"
                }
            });
        })


    </script>
}

Areas/Admin/Views/Course_Detail/Edit.cshtml
@{
    ViewBag.Title = "Sửa bài giảng";
    Layout = "~/Areas/Admin/Views/Shared/_layout.cshtml";
    var detail = ViewBag.detail as HocTrucTuyen.Models.Entity.Course_Detail;
}

<div id="page-wrapper" style="min-height: 356px;">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Sửa bài giảng cho khóa học: <span style="color: blue">@detail.Course.Title</span></h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Sửa bài giảng
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-6">
                                @using (Html.BeginForm("Edit", "Course_Detail", FormMethod.Post, new { id = "frmAddCourse", enctype = "multipart/form-data" }))
                                {
                                    <input type="hidden" name="ID" value="@detail.ID" />
                                    <div class="form-group">
                                        <label>Tên bài giảng</label><span style="color:red">(*)</span>
                                        <input type="text" class="form-control" value="@detail.Name" name="Name" placeholder="Nhập tiêu đề">
                                    </div>
                                    <div class="form-group">
                                        <label>Link Youtube</label><span style="color:red">(*)</span>
                                        <input type="text" class="form-control" value="@detail.Link" name="Link" placeholder="Nhập link youtube" />
                                    </div>
                                    <div class="form-group">
                                        <label>Nội dung </label><span style="color:red">(*)</span>
                                        <textarea name="Descriptions" id="text_Description" rows="6" placeholder="Nhập nội dung" class="form-control">
                                        @detail.Descriptions
                                        </textarea>
                                    </div>

                                    <button type="submit" class="btn btn-default">Sửa</button>
                                }

                            </div>

                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>

@section jsFooter{

    <script type="text/javascript">

        $(document).ready(function () {
            CKEDITOR.replace('text_Description');
            //validate form
            $("#frmAddCourse").validate({
                rules: {
                    Name: "required",
                    Link: "required",
                    Descriptions: "required"
                },
                messages: {
                    Name: "Vui lòng nhập tên bài giảng",
                    Link: "Vui lòng nhập link youtube",
                    Descriptions: "Vui lòng nhập nội dung"
                }
            });
        })


    </script>
}

Areas/Admin/Views/Course_Detail/Index.cshtml
@{
    ViewBag.Title = "Quản lý bài giảng";
    Layout = "~/Areas/Admin/Views/Shared/_layout.cshtml";
    int dem = 1;
    var course = ViewBag.Course as HocTrucTuyen.Models.Entity.Course;
}


@model PagedList.IPagedList<HocTrucTuyen.Models.Entity.Course_Detail>
@using PagedList.Mvc



<div id="page-wrapper" style="min-height: 356px;">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Chi tiết khóa học: <span style="color: blue">@course.Title</span></h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            @if (TempData["add_success"] != null)
            {
                <div class="alert alert-success text-center" id="AlertBox">
                    @TempData["add_success"]
                </div>
            }
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    @*<div class="panel-heading">
                            DataTables Advanced Tables
                        </div>*@
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                <div class="row">
                                    <div class="col-sm-6" style="margin-bottom: 10px;">
                                        <div class="right">
                                            <a class="btn btn-success" href="/Admin/Course_Detail/Add/@course.ID"><i class="fa fa-plus"></i>Thêm mới</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" role="grid" aria-describedby="dataTables-example_info">
                                            <thead>
                                                <tr role="row">
                                                    <th>
                                                        STT
                                                    </th>
                                                    <th>
                                                        Tên bài giảng
                                                    </th>
                                                    <th>
                                                        Nội dung
                                                    </th>
                                                    <th>
                                                        Ngày tạo
                                                    </th>
                                                    <th>

                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @if (Model != null)
                                                {
                                                    foreach (var item in Model)
                                                    {

                                                <tr class="gradeA odd" role="row">
                                                    <td class="sorting_1">@dem</td>
                                                    <td>@item.Name</td>
                                                    <td><div class="scoll_description">@Html.Raw(item.Descriptions)</div></td>
                                                    <td class="text-center">@item.Created_Date</td>
                                                    <td class="center text-center" style="width: 150px">
                                                        <a class="btn btn-primary" href="/Admin/Course_Detail/Edit/@item.ID" title="Sửa bài giảng"><i class="fa fa-edit"></i></a>

                                                        <button class="btn btn-danger btnDelete" title="Xóa bài giảng" data-id="@item.ID"><i class="fa fa-times"></i></button>
                                                  
                                                   
                                                </tr>
                                                   
                                                    

                                                    dem++;
                                                }
                                            }
                                                </tbody>
                                            </table>
                                    </div>
                                </div>
                                @Html.PagedListPager(Model, page => Url.Action("Index", new { ID = course.ID, page, pagesize = Model.PageSize }))
                            </div>
                        </div>

                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>


@section jsFooter{

    <script type="text/javascript">
        $(function () {
            //nếu không có thao tác gì thì ẩn đi
            $('#AlertBox').removeClass('hide');

            //Sau khi hiển thị lên thì delay 1s và cuộn lên trên sử dụng slideup
            $('#AlertBox').delay(2000).slideUp(500);
          


            $('.btnDelete').off('click').on('click', function () {
                const notice = PNotify.notice({
                    title: 'Thông báo',
                    text: 'Bạn thật sự muốn xóa?',
                    icon: 'fa fa-question-circle',
                    width: '360px',
                    minHeight: '110px',
                    hide: false,
                    closer: false,
                    sticker: false,
                    destroy: true,
                    stack: new PNotify.Stack({
                        dir1: 'down',
                        modal: true,
                        firstpos1: 25,
                        overlayClose: false
                    }),
                    modules: new Map([
                        ...PNotify.defaultModules,
                        [PNotifyConfirm, {
                            confirm: true
                        }]
                    ])
                });

                notice.on('pnotify:confirm', () =>
                    $.ajax({
                        data: { ID: $(this).data('id') },
                        url: '/Admin/Course_Detail/Delete',
                        dataType: 'Json',
                        type: 'POST',
                        success: function (res) {
                            if (res.status == true) {

                                window.location.href = "/Admin/Course_Detail/Index/" + @course.ID;
                                PNotify.success({
                                    title: 'THÔNG BÁO!!',
                                    text: 'Xóa bài giảng thành công.'
                                });
                            } else {

                                window.location.href = "/Admin/Course_Detail/Index/" + @course.ID;
                                PNotify.error({
                                    title: 'THÔNG BÁO!!',
                                    text: 'Xóa bài giảng KHÔNG thành công.'
                                });
                            }
                        }
                    })

                );


            });
        });
     

    </script>
}